# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_pin_window(object):
    def setupUi(self, change_pin_window):
        change_pin_window.setObjectName("change_pin_window")
        change_pin_window.resize(800, 600)
        change_pin_window.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.centralwidget = QtWidgets.QWidget(change_pin_window)
        self.centralwidget.setObjectName("centralwidget")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(30, 140, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.username_label.setObjectName("username_label")
        self.log_label = QtWidgets.QLabel(self.centralwidget)
        self.log_label.setGeometry(QtCore.QRect(690, 10, 101, 91))
        self.log_label.setText("")
        self.log_label.setPixmap(QtGui.QPixmap("../images/Bank logo 1.png"))
        self.log_label.setObjectName("log_label")
        self.username_input = QtWidgets.QLineEdit(self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(270, 140, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.username_input.setFont(font)
        self.username_input.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 170, 255);")
        self.username_input.setText("")
        self.username_input.setObjectName("username_input")
        self.change_pin_label = QtWidgets.QLabel(self.centralwidget)
        self.change_pin_label.setGeometry(QtCore.QRect(330, 20, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.change_pin_label.setFont(font)
        self.change_pin_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.change_pin_label.setObjectName("change_pin_label")
        self.confirm_button = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_button.setGeometry(QtCore.QRect(410, 470, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_button.setFont(font)
        self.confirm_button.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.confirm_button.setObjectName("confirm_button")
        self.pin_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pin_input.setGeometry(QtCore.QRect(270, 250, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pin_input.setFont(font)
        self.pin_input.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 170, 255);")
        self.pin_input.setText("")
        self.pin_input.setObjectName("pin_input")
        self.pin_label = QtWidgets.QLabel(self.centralwidget)
        self.pin_label.setGeometry(QtCore.QRect(30, 250, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pin_label.setFont(font)
        self.pin_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.pin_label.setObjectName("pin_label")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(70, 470, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.cancel_button.setObjectName("cancel_button")
        self.balance_input = QtWidgets.QLineEdit(self.centralwidget)
        self.balance_input.setGeometry(QtCore.QRect(270, 350, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.balance_input.setFont(font)
        self.balance_input.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 170, 255);")
        self.balance_input.setText("")
        self.balance_input.setObjectName("balance_input")
        self.balance_label = QtWidgets.QLabel(self.centralwidget)
        self.balance_label.setGeometry(QtCore.QRect(10, 350, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.balance_label.setFont(font)
        self.balance_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.balance_label.setObjectName("balance_label")
        change_pin_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(change_pin_window)
        self.statusbar.setObjectName("statusbar")
        change_pin_window.setStatusBar(self.statusbar)

        self.retranslateUi(change_pin_window)
        QtCore.QMetaObject.connectSlotsByName(change_pin_window)

    def retranslateUi(self, change_pin_window):
        _translate = QtCore.QCoreApplication.translate
        change_pin_window.setWindowTitle(_translate("change_pin_window", "Change Pin"))
        self.username_label.setText(_translate("change_pin_window", "Username"))
        self.change_pin_label.setText(_translate("change_pin_window", "Add Account"))
        self.confirm_button.setText(_translate("change_pin_window", "CONFIRM"))
        self.pin_label.setText(_translate("change_pin_window", "Pin"))
        self.cancel_button.setText(_translate("change_pin_window", "CANCEL"))
        self.balance_label.setText(_translate("change_pin_window", "Initial Balance \n"
"(₱ 100 above)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    change_pin_window = QtWidgets.QMainWindow()
    ui = Ui_change_pin_window()
    ui.setupUi(change_pin_window)
    change_pin_window.show()
    sys.exit(app.exec_())
