# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BalanceInquiry.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_withdraw_window(object):
    def setupUi(self, withdraw_window):
        withdraw_window.setObjectName("withdraw_window")
        withdraw_window.resize(800, 600)
        withdraw_window.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.centralwidget = QtWidgets.QWidget(withdraw_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 140, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(690, 10, 101, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../images/Bank logo 1.png"))
        self.label_2.setObjectName("label_2")
        self.input_deposit = QtWidgets.QLineEdit(self.centralwidget)
        self.input_deposit.setGeometry(QtCore.QRect(270, 140, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.input_deposit.setFont(font)
        self.input_deposit.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 170, 255);")
        self.input_deposit.setObjectName("input_deposit")
        withdraw_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(withdraw_window)
        self.statusbar.setObjectName("statusbar")
        withdraw_window.setStatusBar(self.statusbar)

        self.retranslateUi(withdraw_window)
        QtCore.QMetaObject.connectSlotsByName(withdraw_window)

    def retranslateUi(self, withdraw_window):
        _translate = QtCore.QCoreApplication.translate
        withdraw_window.setWindowTitle(_translate("withdraw_window", "Balance Inquiry"))
        self.label.setText(_translate("withdraw_window", "Your Balance is"))
        self.input_deposit.setText(_translate("withdraw_window", "₱"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    withdraw_window = QtWidgets.QMainWindow()
    ui = Ui_withdraw_window()
    ui.setupUi(withdraw_window)
    withdraw_window.show()
    sys.exit(app.exec_())
