# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Deposit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deposit_window(object):
    def setupUi(self, deposit_window):
        deposit_window.setObjectName("deposit_window")
        deposit_window.resize(800, 600)
        deposit_window.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.centralwidget = QtWidgets.QWidget(deposit_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 140, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(690, 10, 101, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../images/Bank logo 1.png"))
        self.label_2.setObjectName("label_2")
        self.input_deposit = QtWidgets.QLineEdit(self.centralwidget)
        self.input_deposit.setGeometry(QtCore.QRect(370, 140, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.input_deposit.setFont(font)
        self.input_deposit.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 170, 255);")
        self.input_deposit.setObjectName("input_deposit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 250, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        deposit_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(deposit_window)
        self.statusbar.setObjectName("statusbar")
        deposit_window.setStatusBar(self.statusbar)

        self.retranslateUi(deposit_window)
        QtCore.QMetaObject.connectSlotsByName(deposit_window)

    def retranslateUi(self, deposit_window):
        _translate = QtCore.QCoreApplication.translate
        deposit_window.setWindowTitle(_translate("deposit_window", "Deposit"))
        self.label.setText(_translate("deposit_window", "Input amount to deposit"))
        self.input_deposit.setText(_translate("deposit_window", "₱"))
        self.pushButton.setText(_translate("deposit_window", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deposit_window = QtWidgets.QMainWindow()
    ui = Ui_deposit_window()
    ui.setupUi(deposit_window)
    deposit_window.show()
    sys.exit(app.exec_())
